sonar.projectKey=Moustapha9999_el-amana-immo
sonar.organization=moustapha9999
sonar.projectName=el-amana-immo
sonar.sourceEncoding=UTF-8

sonar.sources=backend/app,frontend/angular20/src
sonar.tests=backend/tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,**/__pycache__/**,**/coverage/**,**/migrations/**,**/alembic/versions/**
sonar.python.version=3.13
